### ISSUE TITLE
[Feature Request] Clean External Links, i.e. Circumvent Facebook's Redirected

### ISSUE THREAD

**Issue by Mosrite** [indywidualny/FacebookLite#11]
Hello everyone, as you probably know every external link that is shared on Facebook gets redirected via Facebook if you click it. (If you don't know what I mean, just hover over an external link on Facebook's desktop version and look where it's heading to.) Thereby, Facebook is aware of every link you click.
It would be great, if the app would feature an option to "clean" these external links, i.e. don't use Facebook's redirect service, but go directly to the actual links instead.

Thanks for considering my suggestion!

**Comment by indywidualny** [comment]
I know that but I don't know if it's possible to achieve it. To copy the real link, the Facebook link have to be clicked and Facebook redirects us to the source link. So Facebook is aware of that click. "Cleaning"  these links would also require being redirected by Facebook. Otherwise there is no possibility to get source link. Finally you would get "the real" address but Facebook would be aware of that click anyway. They did it the way it is.

So even if the "cleaning" was introduced and the app would do it itself, Facebook would still know about the click. They just have to know that, to give us the real address. One cannot simply trick them.

**Comment by Mosrite** [comment]
There are some Firefox addons that can actually do this, so there's gotta be a way around it. I don't even think it is very hard. Doesn't all these links have the same scheme? facebook.com/l.php?u=[URL]&[something] - so maybe the [URL]-part of that scheme could just be filtered?
I'm not a programmer though, so I don't know if that's gonna work.

**Comment by indywidualny** [comment]
You are right. I didn't notice it before. All the redirections are so easy to get. I will try to do it in the next update. 

My previous answer is based on my assumptions. I should have checked it. Sorry :)

**Comment by Mosrite** [comment]
That's great, thanks!
And no need for apologizing! As I said, I'm not even sure, if it really works this way, but maybe it's worth looking into it! :)

**Comment by indywidualny** [comment]
Ok, I did it. It's perfect. Wait to next update :)

**Comment by Mosrite** [comment]
Awesome, can't wait for this to be implemented! :)

**Comment by indywidualny** [comment]
Ok. It's will be online tomorrow or on Monday. I'm closing the issue.
