### ISSUE TITLE
New permissions

### ISSUE THREAD

**Issue by logos88** [indywidualny/FacebookLite#14]
Hello. I was going to update facebook lite and I have noticed that new permissions are required. What are they needed for? why does it need the identity of the phone? One of the coolest things of this app was that it needs a lot of less permissions than the original facebook app

**Comment by indywidualny** [comment]
Hi, let me explain new permissions.

"Why does it need the identity of the phone?" - it actually doesn't. I have no idea why it's listed during instalation. All the permissions are definied in the file below. I suppose it's because of ACCESS_NETWORK_STATE but the app really don't need and don't use the identity of the phone.

https://github.com/indywidualny/FacebookLite/blob/master/app/src/main/AndroidManifest.xml
* android.permission.INTERNET"
* android.permission.ACCESS_NETWORK_STATE"
* android.permission.WRITE_EXTERNAL_STORAGE"
* android.permission.RECEIVE_BOOT_COMPLETED"
* android.permission.VIBRATE"

INTERNET is obvious, we need access to the Internet to do anything.

ACCESS_NETWORK_STATE is needed to check if there is access to the Internet and it makes possible to determine connection type (mobile or Wi-Fi). It helps to decide when to use Facebook Zero. It's basically checking state of the network.

WRITE_EXTERNAL_STORAGE is for saving camera photos and it also grant access to files during photo upload.

RECEIVE_BOOT_COMPLETED is for auto-starting notifications service after booting the device if the service was configured and activated before.

VIBRATE is for enabling vibrations for notifications.

**Comment by logos88** [comment]
Oks, thanks for the explanation! :)
