### ISSUE TITLE
Upload photos

### ISSUE THREAD

**Issue by arnef** [indywidualny/FacebookLite#9]
Can't select a photo to upload or opening camera

**Comment by indywidualny** [comment]
It may not work on some KitKat versions due to https://code.google.com/p/android/issues/detail?id=62220

I'm really sorry. There is nothing I can do in that case. Hopefully it's working on most KitKat devices so the only thing to do is Android system update (if possible) or updating https://play.google.com/store/apps/details?id=com.google.android.webview (app not available for all the devices). 

Again - I'm really sorry. I wrote about that behaviour somewhere at README.
